name: ${project.artifactId}
version: ${project.version}
api-version: 1.14
description: ${project.description}
author: mattboy9921 (mattboy9921@aim.com)
main: net.mattlabs.mauvelist.MauveList
permissions:
  mauvelist.grey:
    description: Makes user part of the greylist and deletes their player data on quit.